theme: jekyll-theme-minimal
title: Ho-Yang Tsai
description: 
logo: 
google_analytics: G-6219R1CH71
exclude: ["Gemfile", "Gemfile.lock", "run.sh"]
languages: ['en', 'zh-tw']

plugins:
  - "jekyll-github-metadata"